text1 = input("Введите первое число:")
text2 = input("Введите второе число:")
text3 = input("Введите третье число:")
number1 = float(text1)
number2 = float(text2)
number3 = float(text3)
tree = (number1 > 0) and (number2 > 0) and (number3 > 0)
one = (number1 > 0) ^ (number2 > 0) ^ (number3 > 0)
two = ((number1 > 0) and (number2 > 0)) ^ ((number1 > 0) and (number3 > 0)) ^ ((number2 > 0) and (number3 > 0))
zero = (number1 < 0) and (number2 < 0) and (number3 < 0)
print("Вы ввели одно положительное число:", one)
print("Вы ввели два положительных числа:", two)
print("Вы ввели три положительных числа:", tree)
print("Вы не ввели ни одного положительного числа:", zero)
