text1 = input("Введите первое число:")
text2 = input("Введите второе число:")
text3 = input("Введите третье число:")
number1 = float(text1)
number2 = float(text2)
number3 = float(text3)
print("Первое число положительное:", (number1 > 0))
print("Первое число отрицательное:", (number1 < 0))
print("Второе число положительное:", (number2 > 0))
print("Второе число отрицательное:", (number2 < 0))
print("Третье число положительное:", (number3 > 0))
print("Третье число отрицательное:", (number3 < 0))
